
import { User, FeedItem, FeedItemType, Vendor, VendorCategory, Event, Review, Product } from './types';

export const mockUser: User = {
  id: '1',
  name: 'Alex Johnson',
  role: 'user',
  avatar: 'https://picsum.photos/seed/user1/200',
  points: 1250,
  level: 3,
  badges: ['Early Adopter', 'Community Star', 'Event Master'],
  savedItems: ['1', '3'],
  likedItems: ['1', '2', 'q1'],
  following: ['1', '3'],
};

export const mockFeedData: FeedItem[] = [
  {
    id: '1',
    type: FeedItemType.VendorHighlight,
    author: 'Island Spice Co.',
    authorAvatar: 'https://picsum.photos/seed/vendor1/100',
    timestamp: '2 hours ago',
    title: 'New Scotch Bonnet Hot Sauce!',
    caption: 'Check out our new hot sauce blend! Made with locally grown scotch bonnet peppers.',
    media: 'https://picsum.photos/seed/spice/800/600',
    likes: 45,
    comments: 12,
    shares: 8,
  },
  {
    id: '2',
    type: FeedItemType.Video,
    author: 'SVG Tourism Board',
    authorAvatar: 'https://picsum.photos/seed/tourism/100',
    timestamp: '4 hours ago',
    title: 'Discover the Beauty of SVG',
    caption: 'Join us this weekend for the Regatta. Fun, sun, and sea!',
    media: 'https://picsum.photos/seed/boat/800/600',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    likes: 112,
    comments: 28,
    shares: 15,
  },
  {
    id: '3',
    type: FeedItemType.Poll,
    author: 'Everything Vincy',
    authorAvatar: 'https://picsum.photos/seed/ev/100',
    timestamp: '8 hours ago',
    title: "What's your favorite local dish?",
    caption: 'Help us decide the theme for next month\'s food festival!',
    pollOptions: [
      { id: 'a', text: 'Roasted Breadfruit', votes: 45 },
      { id: 'b', text: 'Callaloo Soup', votes: 32 },
      { id: 'c', text: 'Fried Plantain', votes: 28 },
      { id: 'd', text: 'Fish & Chips', votes: 19 },
    ],
    totalVotes: 124,
    likes: 89,
    comments: 41,
    shares: 15,
  },
    {
    id: '4',
    type: FeedItemType.UserContent,
    author: 'Maria\'s Craft Corner',
    authorAvatar: 'https://picsum.photos/seed/user2/100',
    timestamp: '6 hours ago',
    caption: 'New handwoven baskets just finished! Each one tells a story of our island heritage.',
    media: 'https://picsum.photos/seed/baskets/800/600',
    likes: 67,
    comments: 18,
    shares: 5,
  },
  {
    id: 'q1',
    type: FeedItemType.Quiz,
    author: 'SVG History Buffs',
    authorAvatar: 'https://picsum.photos/seed/history/100',
    timestamp: '1 day ago',
    title: 'How well do you know Vincy history?',
    caption: 'Test your knowledge with our weekly history quiz!',
    likes: 55,
    comments: 10,
    shares: 4,
    quiz: {
      questions: [
        {
          question: "What is the national bird of St. Vincent & the Grenadines?",
          options: [
            { id: 'q1a', text: 'The Vincy Parrot' },
            { id: 'q1b', text: 'The Brown Pelican' },
            { id: 'q1c', text: 'The Magnificent Frigatebird' },
          ],
          correctAnswerId: 'q1a'
        },
        {
          question: "Which famous movie franchise filmed scenes in St. Vincent?",
          options: [
            { id: 'q2a', text: 'James Bond' },
            { id: 'q2b', text: 'Pirates of the Caribbean' },
            { id: 'q2c', text: 'Jurassic Park' },
          ],
          correctAnswerId: 'q2b'
        }
      ]
    }
  },
];

const mockReviews: Review[] = [
    { id: 'r1', author: 'Jane Doe', avatar: 'https://picsum.photos/seed/rev1/100', rating: 5, comment: 'Absolutely the best spices on the island! The jerk seasoning is a must-try.', timestamp: '2 days ago' },
    { id: 'r2', author: 'John Smith', avatar: 'https://picsum.photos/seed/rev2/100', rating: 4, comment: 'Great products and friendly staff. A bit pricey but worth it for the quality.', timestamp: '1 week ago'},
    { id: 'r3', author: 'Emily White', avatar: 'https://picsum.photos/seed/rev3/100', rating: 5, comment: 'I love their selection of local teas. A true taste of Vincy.', timestamp: '3 weeks ago'},
];

const mockProducts: Product[] = [
    {id: 'p1', name: 'Scotch Bonnet Hot Sauce', image: 'https://picsum.photos/seed/prod1/400', price: '$15.00', description: 'A fiery and flavorful hot sauce made from locally sourced scotch bonnet peppers. A staple for any Caribbean kitchen.'},
    {id: 'p2', name: 'All-Purpose Seasoning', image: 'https://picsum.photos/seed/prod2/400', price: '$12.50', description: 'Our signature blend of herbs and spices, perfect for meats, fish, and vegetables. Enhances any dish with authentic island flavor.'},
    {id: 'p3', name: 'Jerk Marinade', image: 'https://picsum.photos/seed/prod3/400', price: '$18.00', description: 'A rich and spicy marinade that brings the classic taste of jerk to your grill. Marinate for at least 4 hours for best results.'},
    {id: 'p4', name: 'Local Herbal Tea Blend', image: 'https://picsum.photos/seed/prod4/400', description: 'A calming blend of local herbs like lemongrass and soursop leaf. Perfect for a relaxing evening.'},
];


export const mockVendors: Vendor[] = [
  {
    id: '1',
    name: 'Island Spice Co.',
    category: VendorCategory.Food,
    description: 'Authentic Caribbean spices and seasonings made from locally grown ingredients. We\'ve been serving the community for over 15 years with traditional recipes passed down through generations.',
    image: 'https://picsum.photos/seed/spice-store/800/600',
    rating: 4.8,
    reviewsCount: 124,
    followersCount: 2300,
    location: 'Kingstown, St. Vincent',
    featured: true,
    premium: true,
    reviews: mockReviews,
    showcaseImages: ['https://picsum.photos/seed/showcase1/600/400', 'https://picsum.photos/seed/showcase2/600/400', 'https://picsum.photos/seed/showcase3/600/400'],
    products: mockProducts,
  },
  {
    id: '2',
    name: 'Caribbean Craft Corner',
    category: VendorCategory.Crafts,
    description: 'Handmade jewelry, pottery, and artwork celebrating Vincentian culture.',
    image: 'https://picsum.photos/seed/crafts/800/600',
    rating: 4.6,
    reviewsCount: 89,
    followersCount: 1200,
    location: 'Bequia',
    featured: false,
    premium: false,
    reviews: mockReviews.slice(0,1),
    showcaseImages: ['https://picsum.photos/seed/showcase4/600/400'],
    products: [
      {id: 'p5', name: 'Handwoven Basket', image: 'https://picsum.photos/seed/prod5/400', price: '$45.00', description: 'Beautifully crafted baskets made from local materials. Strong, durable, and stylish.'},
      {id: 'p6', name: 'Clay Pottery Vase', image: 'https://picsum.photos/seed/prod6/400', price: '$60.00', description: 'A unique, hand-thrown clay vase, perfect for adding a touch of local art to your home.'},
    ],
  },
  {
    id: '3',
    name: 'Bequia Boat Tours',
    category: VendorCategory.Tours,
    description: 'Island hopping adventures and sunset cruises around the Grenadines.',
    image: 'https://picsum.photos/seed/tours/800/600',
    rating: 4.9,
    reviewsCount: 203,
    followersCount: 5400,
    location: 'Port Elizabeth, Bequia',
    featured: true,
    premium: true,
    reviews: mockReviews.slice(1,2),
    showcaseImages: ['https://picsum.photos/seed/showcase5/600/400', 'https://picsum.photos/seed/showcase6/600/400'],
    products: [
      {id: 'p7', name: 'Sunset Cruise', image: 'https://picsum.photos/seed/prod7/400', price: '$150 / person', description: 'Experience a breathtaking Caribbean sunset from the water. Drinks and light snacks included.'},
      {id: 'p8', name: 'Full-Day Island Hop', image: 'https://picsum.photos/seed/prod8/400', price: '$300 / group', description: 'Explore the stunning Grenadine islands on a private tour. Snorkeling gear provided.'},
    ],
  },
  {
    id: '4',
    name: 'Vincy Fresh Produce',
    category: VendorCategory.Agriculture,
    description: 'Farm-fresh fruits and vegetables from local farmers across SVG.',
    image: 'https://picsum.photos/seed/produce/800/600',
    rating: 4.7,
    reviewsCount: 67,
    followersCount: 850,
    location: 'Multiple Locations',
    featured: false,
    premium: false,
    reviews: [],
    showcaseImages: [],
    products: [],
  },
];

export const mockEvents: Event[] = [
  {
    id: 'e1',
    title: 'Vincy Mas 2024 Launch',
    description: 'Official launch of this year\'s carnival celebrations with live music and cultural performances.',
    image: 'https://picsum.photos/seed/mas/800/600',
    date: '2024-07-05',
    time: '18:00',
    location: 'Victoria Park',
    category: 'Cultural',
    price: 'Free',
    attendees: 450,
    featured: true,
    participants: [mockVendors[0], mockVendors[1]]
  },
  {
    id: 'e2',
    title: 'Blue Economy Summit',
    description: 'Learn about sustainable ocean practices and marine conservation efforts.',
    image: 'https://picsum.photos/seed/summit/800/600',
    date: '2024-07-22',
    time: '09:00',
    location: 'Peace Memorial Hall',
    category: 'Educational',
    price: '$25',
    attendees: 120,
    featured: false,
  },
  {
    id: 'e3',
    title: 'Farmers Market Festival',
    description: 'Celebrate local agriculture with fresh produce, cooking demos, and live music.',
    image: 'https://picsum.photos/seed/market/800/600',
    date: '2024-08-03',
    time: '08:00',
    location: 'Kingstown Market Square',
    category: 'Food',
    price: 'Free',
    attendees: 230,
    featured: false,
  },
  {
    id: 'e4',
    title: 'National Heroes Day Celebration',
    description: 'A day of remembrance and celebration for the national heroes of SVG.',
    image: 'https://picsum.photos/seed/heroes/800/600',
    date: '2024-03-14',
    time: '10:00',
    location: 'Obelisk at Dorsetshire Hill',
    category: 'National',
    price: 'Free',
    attendees: 500,
    featured: false,
  },
  {
    id: 'e5',
    title: 'Bequia Music Fest',
    description: 'Annual music festival featuring local and international artists.',
    image: 'https://picsum.photos/seed/musicfest/800/600',
    date: '2024-01-28',
    time: '19:00',
    location: 'Bequia',
    category: 'Music',
    price: '$50',
    attendees: 1200,
    featured: false,
  },
];